export default Object.freeze([
  { content: 'AC', type: '' },
  { content: '+/-', type: '' },
  { content: '%', type: '' },
  { content: '÷', type: 'operation' },
  { content: '7', type: 'number' },
  { content: '8', type: 'number' },
  { content: '9', type: 'number' },
  { content: 'x', type: 'operation' },
  { content: '4', type: 'number' },
  { content: '5', type: 'number' },
  { content: '6', type: 'number' },
  { content: '-', type: 'operation' },
  { content: '1', type: 'number' },
  { content: '2', type: 'number' },
  { content: '3', type: 'number' },
  { content: '+', type: 'operation' },
  { content: '0', type: 'number' },
  { content: '.', type: 'number' },
  { content: '=', type: 'equal' },
])
